// Code generated by go-enum DO NOT EDIT.
// Version: example
// Revision: example
// Build Date: example
// Built By: example

//go:build example
// +build example

package example

import (
	"errors"
	"fmt"
	"strings"
)

const (
	// RiskLevelNormal is a RiskLevel of type Normal.
	// No risk
	RiskLevelNormal RiskLevel = iota
	// RiskLevelLow is a RiskLevel of type Low.
	// Low risk
	RiskLevelLow
	// RiskLevelMedium is a RiskLevel of type Medium.
	// Medium risk
	RiskLevelMedium
	// RiskLevelHigh is a RiskLevel of type High.
	// High risk
	RiskLevelHigh
)

var ErrInvalidRiskLevel = errors.New("not a valid RiskLevel")

const _RiskLevelName = "normallowmediumhigh"

var _RiskLevelMap = map[RiskLevel]string{
	RiskLevelNormal: _RiskLevelName[0:6],
	RiskLevelLow:    _RiskLevelName[6:9],
	RiskLevelMedium: _RiskLevelName[9:15],
	RiskLevelHigh:   _RiskLevelName[15:19],
}

// String implements the Stringer interface.
func (x RiskLevel) String() string {
	if str, ok := _RiskLevelMap[x]; ok {
		return str
	}
	return fmt.Sprintf("RiskLevel(%d)", x)
}

const _RiskLevelTagRU = "Риска рискнизкий рискСредний рискВысокий риск"

var _RiskLevelTagRUMap = map[RiskLevel]string{
	RiskLevelNormal: _RiskLevelTagRU[0:19],
	RiskLevelLow:    _RiskLevelTagRU[19:40],
	RiskLevelMedium: _RiskLevelTagRU[40:63],
	RiskLevelHigh:   _RiskLevelTagRU[63:86],
}

// TagRU returns the RU tag value.
func (x RiskLevel) TagRU() string {
	return _RiskLevelTagRUMap[x]
}

const _RiskLevelTagZH = "无风险低风险中风险高风险"

var _RiskLevelTagZHMap = map[RiskLevel]string{
	RiskLevelNormal: _RiskLevelTagZH[0:9],
	RiskLevelLow:    _RiskLevelTagZH[9:18],
	RiskLevelMedium: _RiskLevelTagZH[18:27],
	RiskLevelHigh:   _RiskLevelTagZH[27:36],
}

// TagZH returns the ZH tag value.
func (x RiskLevel) TagZH() string {
	return _RiskLevelTagZHMap[x]
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x RiskLevel) IsValid() bool {
	_, ok := _RiskLevelMap[x]
	return ok
}

var _RiskLevelValue = map[string]RiskLevel{
	_RiskLevelName[0:6]:                    RiskLevelNormal,
	strings.ToLower(_RiskLevelName[0:6]):   RiskLevelNormal,
	_RiskLevelName[6:9]:                    RiskLevelLow,
	strings.ToLower(_RiskLevelName[6:9]):   RiskLevelLow,
	_RiskLevelName[9:15]:                   RiskLevelMedium,
	strings.ToLower(_RiskLevelName[9:15]):  RiskLevelMedium,
	_RiskLevelName[15:19]:                  RiskLevelHigh,
	strings.ToLower(_RiskLevelName[15:19]): RiskLevelHigh,
}

// ParseRiskLevel attempts to convert a string to a RiskLevel.
func ParseRiskLevel(name string) (RiskLevel, error) {
	if x, ok := _RiskLevelValue[name]; ok {
		return x, nil
	}
	return RiskLevel(0), fmt.Errorf("%s is %w", name, ErrInvalidRiskLevel)
}

// MarshalText implements the text marshaller method.
func (x RiskLevel) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *RiskLevel) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseRiskLevel(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *RiskLevel) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
